service: aws-java-simple-http-endpoint

provider:
  name: aws
  runtime: java8

package:
  artifact: target/aws-java-simple-http-endpoint-dev.jar

functions:
  poc:
    handler: com.github.leegphillips.ServerlessPoCs.awsJavaSimpleHttpEndpoint.Handler
